#!/bin/bash

# Description: Clean all macOS dot files, include ._*, .DS_Store
# Author:      Yezzi Hsueh <xueye404@foxmail.com>
# Create:      2023-08-17 13:37

# envs
if [ -z "$1" ]; then
    CLEAN_DIR=`pwd`
else
    CLEAN_DIR=`realpath $1`
fi

# start clean process
echo "Cleanning dot files in $CLEAN_DIR"
find $CLEAN_DIR -type f -name '._*' -exec echo "deleting: {}" \; -delete
find $CLEAN_DIR -type f -name '.DS_Store' -exec echo "deleting: {}" \; -delete

find $CLEAN_DIR -type f -name '*.zip' -exec sh -c "unzip -l {} | grep '__MACOSX/' | awk '{print \$4}' |xargs zip -d {}" \;
echo "Done"
